### ISSUE TITLE
Build the initial version

### ISSUE THREAD

**Issue by david-haerer** [david-haerer/apparition#1]
## Tasks

* [x] Setup the `pyproject.toml`.
* [x] Implement the following commands:
  - [x] `apparition install`
    + Install the helper shell function in `~/.zshrc`.
  - [x] `apparition set DESTINATION PATH`
    + Save a new destination.
    + This can also be used to update an existing destination.
  - [x] `apparition remove DESTINATION`
    + Remove a destination.
    + If the destination is unknown the command has no effect.
  - [x] `apparition rename OLD_NAME NEW_NAME`
    + Rename an existing destination.
  - [x] `apparition show`
    + Show all destinations in a table.
  - [x] `apparition show --list`
    + Show all destinations in a list.
  - [x] `apparition show DESTINATION`
    + Only show the path to the given destination.
  - [x] `apparition check`
    + Check all destinations if their path is a directory.
  - [x] `apparition purge`
    + Remove all destinations.
    + The command asks for confirmation before removing all destinations.
  - [x] `apparate DESTINATION`
    + Change the working directory to the path for `DESTINATION` via a shell function.
  - [x] `apparition apparate --unsafe DESTINATION`
    + Change the working directory to the path for `DESTINATION` in pure Python.
    + See [StackOverflow](https://stackoverflow.com/a/75351711/11386095) for reference.
* [x] Style with black, isort and pylint.
* [x] Manual testing on Linux / zsh.
* [x] End-to-end test coverage.
* [x] Document the app in the `README.md`
* [x] Add MIT license.
* [ ] Build the package and publish to PyPi.
